name: hostelp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  json_annotation: ^4.8.0
  routemaster: ^1.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
